name: news_app
description: "A News app for Trivenous intern."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.0+1
  provider: ^6.1.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  lint: ^2.3.0
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: GtPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf
