// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkGYPpg6GvybXD1E_v0yKfE4UdhtWBWQ',
    appId: '1:1058711480990:web:a9abf4a219a5d62f81e98f',
    messagingSenderId: '1058711480990',
    projectId: 'news-app-8bb4a',
    authDomain: 'news-app-8bb4a.firebaseapp.com',
    storageBucket: 'news-app-8bb4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpslqvkZaZt0In4_eZlOJdnOpptMlYAt8',
    appId: '1:1058711480990:android:89a2998b9b610c4a81e98f',
    messagingSenderId: '1058711480990',
    projectId: 'news-app-8bb4a',
    storageBucket: 'news-app-8bb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1Qxya6UqYw0v0v2tpae6enp8P9qUWMQ',
    appId: '1:1058711480990:ios:b814ee8ce70282b081e98f',
    messagingSenderId: '1058711480990',
    projectId: 'news-app-8bb4a',
    storageBucket: 'news-app-8bb4a.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq1Qxya6UqYw0v0v2tpae6enp8P9qUWMQ',
    appId: '1:1058711480990:ios:188b28ab8e08c4d881e98f',
    messagingSenderId: '1058711480990',
    projectId: 'news-app-8bb4a',
    storageBucket: 'news-app-8bb4a.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
